### ISSUE TITLE
Maybe disable autoslide when an arrow is clicked

### ISSUE THREAD

**Issue by johnwatkins0** [mikejandreau/post-slider#4]
To me, when a user clicks an arrow, they are ready to control their own experience. If I'm interested in one of the slides and begin reading the excerpt paragraph, I don't want the next slide to appear automatically when I'm reading.

**Comment by mikejandreau** [comment]
I made the following update from this...

```
// Reset timer for automatic sliding (previous code)
function resetInterval() {
  clearInterval(timer);
  timer = setInterval(function() {
    nextSlide();
  }, timingSlider);
}
```

...to this:

```
// Stop switching slides automatically after arrow is clicked
function resetInterval() {
  clearInterval(timer);
  timer = 0;
}
```

The slides will cycle through automatically and then pause when an arrow is clicked. Seems to work so far.
