### ISSUE TITLE
No jQuery needed

### ISSUE THREAD

**Issue by johnwatkins0** [mikejandreau/post-slider#5]
Since jQuery is not being used inside the main function in scripts.js, that function could be hooked into window load event listener, and the jQuery dependency could be removed entirely. I think this is a good idea in general with plugins since so many sites are trying to avoid jQuery entirely and may avoid plugins that depend on it.

**Comment by mikejandreau** [comment]
Good point. I was debating the jQuery wrap and ended up including it because the plugin wouldn't work in the local version of some themes. I prefer avoiding jQuery whenever possible anyway.
