### ISSUE TITLE
wp_reset_postdata instead of wp_reset_query

### ISSUE THREAD

**Issue by johnwatkins0** [mikejandreau/post-slider#6]
https://github.com/mikejandreau/post-slider/blob/d04a83553a6b95fb178f3ac315b1e3599cb6944a/post-slider.php#L50

Since the plugin is not overriding the global `$wp_query` variable but is overriding the global `$post` by using the `the_post` function, it should use `wp_reset_postdata` to ensure the global post is restored to the page's main queried object. `wp_reset_query` shouldn't be necessary.

**Comment by mikejandreau** [comment]
Updated to use wp_reset_postdata.
